# edited: 2023-08-30

edition = "2021"
version = "Two"


imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 50
fn_params_layout = "Vertical"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true

format_code_in_doc_comments = true

format_macro_matchers = true
format_macro_bodies = true

format_strings = true
hard_tabs = false
hex_literal_case = "Upper"

imports_indent = "Block"
indent_style = "Block"
#imports_granularity = "Module"
newline_style = "Unix"
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# report_fixme = "Always"
# report_todo = "Always"
#group_imports = "StdExternalCrate"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true

wrap_comments = true
