name: Audit Check
on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  check-audit:
    name: Check for vulnerabilities
    runs-on: self-hosted
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - name: Get Sources
        uses: actions/checkout@v2
      - name: Check for vulnerabilities
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

