name: Audit
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  check-audit:
    name: Check
    runs-on: self-hosted
    strategy:
      matrix:
        branch:
          - master
          - develop
    steps:
      - name: Checkout Source Code      
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy, rustfmt
      - name: Run Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
