name: Audit
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  check-audit:
    name: Check
    runs-on: debian-latest
    strategy:
      matrix:
        branch:
          - master
          - develop
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
